import { promises as fs } from "node:fs";
import path from "node:path";

const rootDir = process.cwd();
const srcIconsDir = path.join(rootDir, "src", "icons");
const publicIconsDir = path.join(rootDir, "public", "icons");
const manifestPath = path.join(rootDir, "app", "iconographyManifest.ts");

async function ensureDir(dirPath) {
  await fs.mkdir(dirPath, { recursive: true });
}

async function getSvgFiles(dirPath) {
  const entries = await fs.readdir(dirPath, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".svg"))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
}

function normalizeTitleFromFileName(fileName) {
  return fileName.replace(/^Icon=/, "").replace(/\.svg$/i, "").trim();
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

function buildIconEntries(fileNames) {
  const slugCounts = new Map();

  return fileNames.map((fileName) => {
    const title = normalizeTitleFromFileName(fileName);
    const baseSlug = slugify(title) || "icon";
    const duplicateIndex = slugCounts.get(baseSlug) ?? 0;
    slugCounts.set(baseSlug, duplicateIndex + 1);
    const assetName = duplicateIndex === 0 ? `${baseSlug}.svg` : `${baseSlug}-${duplicateIndex + 1}.svg`;

    return {
      fileName,
      title,
      assetName,
      src: `icons/${assetName}`,
    };
  });
}

async function copyIcons(entries) {
  await ensureDir(publicIconsDir);

  const existingPublicFiles = await getSvgFiles(publicIconsDir);
  const desiredAssetNames = new Set(entries.map((entry) => entry.assetName));

  await Promise.all(
    entries.map((entry) =>
      fs.copyFile(path.join(srcIconsDir, entry.fileName), path.join(publicIconsDir, entry.assetName))
    )
  );

  // Remove stale files that no longer exist in src/icons.
  await Promise.all(
    existingPublicFiles
      .filter((fileName) => !desiredAssetNames.has(fileName))
      .map((fileName) => fs.unlink(path.join(publicIconsDir, fileName)))
  );
}

async function writeManifest(entries) {
  const sortedEntries = [...entries].sort((a, b) => a.title.localeCompare(b.title));
  const lines = [
    "// AUTO-GENERATED by scripts/sync-icons.mjs. Do not edit manually.",
    "export const ICONOGRAPHY_ITEMS = [",
    ...sortedEntries.map(
      (entry) =>
        `  { fileName: ${JSON.stringify(entry.fileName)}, title: ${JSON.stringify(entry.title)}, src: ${JSON.stringify(entry.src)} },`
    ),
    "] as const;",
    "",
  ];

  await fs.writeFile(manifestPath, lines.join("\n"), "utf8");
}

async function main() {
  const sourceFiles = await getSvgFiles(srcIconsDir);
  const iconEntries = buildIconEntries(sourceFiles);
  await copyIcons(iconEntries);
  await writeManifest(iconEntries);
  process.stdout.write(`Synced ${sourceFiles.length} icons.\n`);
}

main().catch((error) => {
  process.stderr.write(`sync-icons failed: ${error.message}\n`);
  process.exit(1);
});
